### PR TITLE
Add way to run tests sans coverage

### LINKED ISSUE #141: Fix stack-traces in tests
Now we have coverage enabled by default the stack traces point at the instrumented code rather than the actual files. 

There might be a setting to fix this via sourcemaps but if not being able to run the tests without the coverage might be a reasonable workaround.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #141

### CODE REVIEW

**Comment by tofumatt** [comment]
This fixes #141, right?

**Comment by muffinresearch** [comment]
heh, yep  - I was just wondering why it wasn't linked :)

**Comment by tofumatt** [comment]
r+ cool!

**Comment by muffinresearch** [comment]
Hmm, travis didn't see this - I wonder why?

**Comment by tofumatt** [comment]
Oh that's weird.

**Comment by muffinresearch** [comment]
Just rebased and re-pushed and now travis is running. Before should have been good enough though. Hey-ho.

**Pull request merged**
