### PR TITLE
Rename XPI metadata to files (close #234)

### LINKED ISSUE #234: Rename XPI "metadata" property to "files"
The metadata property is a bit confusing as we also deal with add-on metadata (#195). We should rename this to `files`.

### PR DESCRIPTION
**Pull request by tofumatt**
I think this clears things up a bit; I really consider this to just be "files" and don't think of it as metadata. And now that we're dealing with Add-on metadata, let's keep the terminology distant :smile:

### CODE REVIEW

**Comment by muffinresearch** [comment]
This is great R+ :sparkles:

**Comment by muffinresearch** [comment]
Also will make it easier when we come to doing #243

**Comment by tofumatt** [comment]
Thanks. I'll rebase this onto master then merge it in.

**Comment by tofumatt** [comment]
I just realised: red and green exactly the same:
red-and-green-the-same

**Pull request merged**
